/camera_node:
  ros__parameters:
    camera_info_url: package://rm_vision_bringup/config/camera_info.yaml
    exposure_time: 3000
    gain: 3.0

/serial_driver:
  ros__parameters:
    timestamp_offset: 0.006
    device_name: /dev/ttyUSB0
    baud_rate: 115200
    flow_control: none
    parity: none
    stop_bits: "1"

/armor_detector:
  ros__parameters:
    debug: true

    detect_color: 0
    binary_thres: 80

    light.min_ratio: 0.1
    armor.min_light_ratio: 0.8

    classifier_threshold: 0.8
    ignore_classes: ["negative"]

/armor_tracker:
  ros__parameters:
    target_frame: odom
    max_armor_distance: 10.0

    ekf:
      sigma2_q_xyz: 0.05
      sigma2_q_yaw: 5.0
      sigma2_q_r: 80.0

      r_xyz_factor: 4e-4
      r_yaw: 5e-3

    tracker:
      max_match_distance: 0.5
      max_match_yaw_diff: 1.0

      tracking_thres: 5
      lost_time_thres: 1.0

/buff_detect:
  ros__parameters:
  # Detector params.
    buff_mode: 4
    color: 1 # 0: blue / 1: red
    max_angle: 0.50  # fan switched angle threshhold
    max_lost_cnt: 5 
    max_v: 4.0  
    max_delta_t: 200.0
    fan_length: 0.7
    no_crop_thres: 0.002

  # Paths.
    camera_param_path: "/config/camera.yaml"
    path_prefix: "/recorder/dataset/"
    
    network_path: "/model/buff-05-28-01.xml"

  # Debug.
    use_roi: false

    show_img: true
    show_all_fans: true
    show_fps: true
    print_target_info: false 
    prinf_latency: false
    assist_label: false
    show_marker: false

/buff_predict:
  ros__parameters:
  # Predict params.
    max_timespan: 20000.0       
    max_rmse: 3.5
    max_v: 3.0
    max_a: 8.0
    history_deque_len_cos: 150
    history_deque_len_phase: 100
    history_deque_len_uniform: 100
    window_size: 2
    delay_small: 250.0
    delay_big: 170.0

  # Paths.
    pf_path: "/config/filter_param.yaml"
    camera_param_path: "/config/camera.yaml"

  # fitting params bound
    #               al  ah    wl   wh    pl    ph    bl  bh
    params_bound: [0.5, 1.2, 1.4, 2.2, -3.14, 3.14, 1.5, 2.5]
    
  # Debug.
    debug: true
    show_img: true
    show_marker: true
    show_fitting_curve: true